### ISSUE TITLE
levels of SNR

### ISSUE THREAD

**Issue by yunzhuC** [DeweiHu/OCT_DDPM#7]
Hello! Great job!
 I would like to ask you how to use three different levels of signal-to-noise ratio (92dB, 96dB, 101dB) to obtain pictures? 
As you said in paper: To test the performance of the model at different speckle levels, the data is acquired with three different levels of signal-to-noise ratio (92dB, 96dB, 101dB).
I want to use my own dataset, but I don't know how to do this step, can you give some advice? Thank you very much!

**Comment by DeweiHu** [comment]
Hi there,

Since we are using our in-house data, the speckle noise level is modulated by attenuating the input signal of the OCT system during acquisition. If you have clean data, you can probably add speckle noise yourself to create noisy dataset.

Dewei
________________________________
From: Chenyunzhu ***@***.***>
Sent: Tuesday, May 30, 2023 10:22 PM
To: DeweiHu/OCT_DDPM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DeweiHu/OCT_DDPM] levels of SNR (Issue #7)


Hello! Great job!
I would like to ask you how to use three different levels of signal-to-noise ratio (92dB, 96dB, 101dB) to obtain pictures?
As you said in paper: To test the performance of the model at different speckle levels, the data is acquired with three different levels of signal-to-noise ratio (92dB, 96dB, 101dB).
I want to use my own dataset, but I don't know how to do this step, can you give some advice? Thank you very much!

**Comment by yunzhuC** [comment]
Thank you for your reply! Please forgive me for having too many questions
Is it possible to add some noise (gaussian noise, salt and pepper noise, speckle noise) to my own dataset and then use your method to denoise? Are there any requirements for the type of these noises? Is it just added in normally? 
Thanks again for your reply! !

**Comment by DeweiHu** [comment]
You can certainly do that to try out the method. Add noise then denoise is a method often used in ultrasound denoising because the clean reference is not accessible. But it is not a common practice for OCT since people managed to get the ground truth via averaging repeated b-scans. But you still need to do a literature review for this.

Dewei
________________________________

**Comment by yunzhuC** [comment]
> 
I get it! I'll try to do it. Thank you.
